### ISSUE TITLE
Uncaught error: Class credentials

### ISSUE THREAD

**Issue by DracoMilesX** [Stickano/startpage#1]
So I wanted to try this startpage but when trying to install it I receive the following error:

/** * Returns the db credentials - used once in the singleton * @return array Credentials */ public function getDb(){ return array('host' => $this->host, 'user' => $this->user, 'pass' => $this->pass, 'db' => $this->db); } } Fatal error: Uncaught Error: Class 'Credentials' not found in /web/startpage/resources/singleton.php:86 Stack trace: #0 /
/web/startpage/resources/singleton.php(39): Singleton::setConn() #1 
/web/startpage/resources/meta.php(4): Singleton::init() #2 
/web/startpage/index.php(7): require_once('/volume4/web/st...') #3 {main} thrown in /web/startpage/resources/singleton.php on line 86

**Comment by Stickano** [comment]
Was a stupid error, that I actually was aware of. I apologize and it has been fixed with latest push.
